# PEI 300 and Major PE Firms List
# Used for tracking buy-side deal activity

PE_FIRMS = [
    # Top 50 by fundraising (PEI 300 2024/2025)
    "KKR",
    "Kohlberg Kravis Roberts",
    "EQT",
    "Blackstone",
    "CVC Capital Partners",
    "CVC",
    "TPG",
    "TPG Capital",
    "Carlyle",
    "Carlyle Group",
    "Thoma Bravo",
    "Advent International",
    "Warburg Pincus",
    "Hg",
    "HgCapital",
    "Clayton Dubilier & Rice",
    "CD&R",
    "Silver Lake",
    "Hellman & Friedman",
    "Vista Equity Partners",
    "Vista Equity",
    "General Atlantic",
    "Clearlake Capital",
    "Clearlake",
    "Goldman Sachs Asset Management",
    "Leonard Green & Partners",
    "Leonard Green",
    "TA Associates",
    "Permira",
    "Bain Capital",
    "Insight Partners",
    "Cinven",
    "Brookfield",
    "Brookfield Asset Management",
    "Genstar Capital",
    "Genstar",
    "Blue Owl Capital",
    "Blue Owl",
    "Francisco Partners",
    "Apollo",
    "Apollo Global Management",
    "New Mountain Capital",
    "Platinum Equity",
    "GTCR",
    "Apax Partners",
    "Apax",
    "BC Partners",
    "PAI Partners",
    "Nordic Capital",
    "Ardian",
    "Partners Group",
    
    # Major Mid-Market (your typical deal size)
    "H.I.G. Capital",
    "HIG Capital",
    "H.I.G.",
    "KPS Capital Partners",
    "KPS Capital",
    "KPS",
    "Aurelius",
    "Aurelius Group",
    "Inflexion",
    "Inflexion Private Equity",
    "Infracapital",
    "American Securities",
    "Cerberus",
    "Cerberus Capital Management",
    "Sun Capital Partners",
    "Sun Capital",
    "Sycamore Partners",
    "Sycamore",
    "Roark Capital",
    "Roark Capital Group",
    "Veritas Capital",
    "Welsh Carson",
    "Welsh Carson Anderson & Stowe",
    "Madison Dearborn",
    "Madison Dearborn Partners",
    "Thomas H. Lee Partners",
    "THL Partners",
    "Providence Equity",
    "Providence Equity Partners",
    "Riverside Company",
    "Riverside Partners",
    "Sentinel Capital Partners",
    "Sentinel Capital",
    "Charterhouse Capital",
    "Charterhouse",
    "Bridgepoint",
    "Bridgepoint Capital",
    "Triton",
    "Triton Partners",
    "Equistone",
    "Equistone Partners",
    "IK Partners",
    "IK Investment Partners",
    "Montagu",
    "Montagu Private Equity",
    "Intermediate Capital Group",
    "ICG",
    "3i",
    "3i Group",
    "Duke Street",
    "Duke Street Capital",
    "OpCapita",
    "Terra Firma",
    "Terra Firma Capital",
    "Graphite Capital",
    "LDC",
    "Livingbridge",
    "Phoenix Equity Partners",
    "Silverfleet Capital",
    "Vitruvian Partners",
    "Vitruvian",
    "Mid Europa Partners",
    "Mid Europa",
    "PAI",
    "Eurazeo",
    "Investcorp",
    "Gulf Capital",
    "AlpInvest",
    "AlpInvest Partners",
    "Coller Capital",
    "HarbourVest",
    "HarbourVest Partners",
    "Pantheon",
    "Pantheon Ventures",
    "Adams Street Partners",
    "Adams Street",
    "Lexington Partners",
    "Hamilton Lane",
    
    # US Mid-Market
    "Oak Hill Capital",
    "Oak Hill Capital Partners",
    "Kelso & Company",
    "Kelso",
    "Lindsay Goldberg",
    "Court Square Capital",
    "Court Square",
    "One Equity Partners",
    "Irving Place Capital",
    "Vestar Capital",
    "Vestar Capital Partners",
    "Olympus Partners",
    "Harvest Partners",
    "Wind Point Partners",
    "Wind Point",
    "Berkshire Partners",
    "Audax",
    "Audax Group",
    "Audax Private Equity",
    "Sterling Partners",
    "Sterling Group",
    "Gryphon Investors",
    "Gryphon",
    "Arsenal Capital",
    "Arsenal Capital Partners",
    "Linden Capital",
    "Linden Capital Partners",
    "Water Street Healthcare",
    "Nautic Partners",
    "Great Hill Partners",
    "Great Hill",
    "Summit Partners",
    "CapStreet",
    "CapStreet Group",
    "Palladin Consumer",
    "Palladin Consumer Retail Partners",
    "TSG Consumer Partners",
    "TSG Consumer",
    "L Catterton",
    "Catterton",
    "Brynwood Partners",
    "Swander Pace Capital",
    "Swander Pace",
    
    # Larkhill Top 80 additions
    "One Rock Capital Partners",
    "One Rock Capital",
    "One Rock",
    "Stellex Capital",
    "Stellex",
    "The Jordan Company",
    "Jordan Company",
    "TJC",
    "Charlesbank",
    "Charlesbank Capital Partners",
    "OMERS Private Equity",
    "OMERS PE",
    "OMERS",
    "CDPQ",
    "La Caisse",
    "Caisse de dépôt",
    "Stone Point Capital",
    "Stone Point",
    "GI Partners",
    "BDT & MSD Partners",
    "BDT Capital",
    "MSD Partners",
    "Stonepeak",
    "Stonepeak Partners",
    "Stonepeak Infrastructure",
    "PAG",
    "PAG Asia",
    "Searchlight Capital",
    "Searchlight Capital Partners",
    "Rhône Group",
    "Rhone Group",
    "Rhône Capital",
    
    # Tech/Software focused
    "Insight Venture Partners",
    "Insight",
    "JMI Equity",
    "JMI",
    "Accel-KKR",
    "K1 Investment Management",
    "K1",
    "Marlin Equity",
    "Marlin Equity Partners",
    "Hg Capital",
    "Symphony Technology Group",
    "STG",
    "Siris Capital",
    "Siris",
    "Thomas Bravo",
    "Vector Capital",
    "TA Associates",
    "Battery Ventures",
    "Warburg Pincus",
    "Welsh Carson",
    
    # European specialists
    "CVC",
    "EQT Partners",
    "Cinven Partners",
    "Permira Advisers",
    "Apax",
    "BC Partners",
    "PAI Partners",
    "Advent International",
    "Bain Capital Europe",
    "KKR Europe",
    "Carlyle Europe",
    "Blackstone Europe",
    "Nordic Capital",
    "EQT",
    "Altor",
    "Altor Equity Partners",
    "CapMan",
    "Verdane",
    "Herkules Capital",
    "FSN Capital",
    "Summa Equity",
    "Norvestor",
    "Polaris",
    "Axcel",
    "Procuritas",
    "AAC Capital",
    "Gilde",
    "Gilde Buy Out Partners",
    "Waterland",
    "Waterland Private Equity",
    "Egeria",
    "NPM Capital",
    "Parcom",
    "Main Capital",
    "Fortino Capital",
    "Gimv",
    "Sofindev",
    "Deutsche Private Equity",
    "DPE",
    "DBAG",
    "Deutsche Beteiligungs",
    "Bregal",
    "Bregal Unternehmerkapital",
    "Quadriga Capital",
    "Halder",
    "Capiton",
    "EMERAM",
    "VR Equitypartner",
    "Orlando Management",
    "Argos Wityu",
    "Ardian France",
    "Astorg",
    "Montefiore Investment",
    "Cathay Capital",
    "Chequers Capital",
    "Keensight Capital",
    "IdInvest",
    "Idinvest Partners",
    "Tikehau Capital",
    "Weinberg Capital",
    "Sagard",
    "PAI Partners",
    "Andera Partners",
    "21 Invest",
    "21 Investimenti",
    "Clessidra",
    "Progressio",
    "Investindustrial",
    "Xenon Private Equity",
    "GPF Capital",
    "MCH Private Equity",
    "Proa Capital",
    "Portobello Capital",
    "Nazca Capital",
    "N+1",
    "Magnum Capital",
    "Sherpa Capital",
    "Corpfin Capital",
    
    # Additional notable firms
    "Golden Gate Capital",
    "Gores Group",
    "Gores",
    "Lone Star Funds",
    "Lone Star",
    "Centerbridge",
    "Centerbridge Partners",
    "Angelo Gordon",
    "Angelo Gordon & Co",
    "Avenue Capital",
    "Ares Management",
    "Ares",
    "Oaktree",
    "Oaktree Capital",
    "Fortress",
    "Fortress Investment Group",
    "Värde Partners",
    "Varde",
    "Tikehau",
    "MidOcean Partners",
    "MidOcean",
    "Littlejohn",
    "Littlejohn & Co",
    "American Industrial Partners",
    "AIP",
    "Atlas Holdings",
    "Atlas",
    "Saw Mill Capital",
    "Mill Point Capital",
    "Mill Point",
    "Industrial Growth Partners",
    "IGP",
    "Odyssey Investment Partners",
    "Odyssey",
    "Mason Wells",
    "GenNx360 Capital Partners",
    "Spell Capital",
    "The Stephens Group",
    "Stephens Group",
    "Bansk Group",
    "Blue Point Capital",
    "Blue Point",
    "Huron Capital",
    "Kian Capital",
    "NewSpring Capital",
    "NewSpring",
    "Pfingsten Partners",
    "Pfingsten",
    "Shore Capital Partners",
    "Shore Capital",
    "Trive Capital",
    "Renovation Capital",
    "PeakEquity Partners",
    "PeakEquity",
]

# Search patterns for PE buyer activity
PE_BUYER_PATTERNS = [
    "{firm} in talks to acquire",
    "{firm} in talks to buy",
    "{firm} circling",
    "{firm} among bidders",
    "{firm} exploring acquisition",
    "{firm} said to be interested",
    "{firm} weighing bid",
    "{firm} considering bid",
    "{firm} eyeing",
    "{firm} looking at",
    "{firm} approached",
    "{firm} has approached",
    "{firm} makes offer",
    "{firm} submits bid",
    "{firm} enters race",
    "{firm} joins bidding",
    "{firm} private equity",
    "private equity {firm}",
    "{firm} backed",
    "{firm}-backed",
]
